version: '3.8'

services:
  backend:
    build:
      context: ./src/nlp/Chatbot/chain
      dockerfile: Dockerfile
    container_name: feedback_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: feedback_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network: